//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlokanUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlokanUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerTable1Image {
            get {
                object obj = ResourceManager.GetObject("answerTable1Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerTable2Image {
            get {
                object obj = ResourceManager.GetObject("answerTable2Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerTable3Image {
            get {
                object obj = ResourceManager.GetObject("answerTable3Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --All--.
        /// </summary>
        internal static string DropdownTextAll {
            get {
                return ResourceManager.GetString("DropdownTextAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaptionGeneral {
            get {
                return ResourceManager.GetString("ErrorCaptionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Table Columns has incorrect format!.
        /// </summary>
        internal static string ErrorTextAnswerTableColumnsFormat {
            get {
                return ResourceManager.GetString("ErrorTextAnswerTableColumnsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Table Rows has incorrect format!.
        /// </summary>
        internal static string ErrorTextAnswerTableRowsFormat {
            get {
                return ResourceManager.GetString("ErrorTextAnswerTableRowsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and White Threshold has incorrect format!.
        /// </summary>
        internal static string ErrorTextBlackWhiteThresholdFormat {
            get {
                return ResourceManager.GetString("ErrorTextBlackWhiteThresholdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Evaluation Type has incorrect format!.
        /// </summary>
        internal static string ErrorTextCellEvaluationTypeFormat {
            get {
                return ResourceManager.GetString("ErrorTextCellEvaluationTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers have not been properly selected!.
        /// </summary>
        internal static string ErrorTextCorrectAnswersNotSelected {
            get {
                return ResourceManager.GetString("ErrorTextCorrectAnswersNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Line Curvature Limit has incorrect format!.
        /// </summary>
        internal static string ErrorTextCrossLineCurvatureLimitFormat {
            get {
                return ResourceManager.GetString("ErrorTextCrossLineCurvatureLimitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Line Length has incorrect format!.
        /// </summary>
        internal static string ErrorTextCrossLineLengthFormat {
            get {
                return ResourceManager.GetString("ErrorTextCrossLineLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Cell Height has incorrect format!.
        /// </summary>
        internal static string ErrorTextDefaultCellHeightFormat {
            get {
                return ResourceManager.GetString("ErrorTextDefaultCellHeightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sheet Width has incorrect format!.
        /// </summary>
        internal static string ErrorTextDefaultSheetWidthFormat {
            get {
                return ResourceManager.GetString("ErrorTextDefaultSheetWidthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected answers have not been properly selected!.
        /// </summary>
        internal static string ErrorTextExpectedAnswersNotSelected {
            get {
                return ResourceManager.GetString("ErrorTextExpectedAnswersNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid student number format..
        /// </summary>
        internal static string ErrorTextInvalidStudentNumber {
            get {
                return ResourceManager.GetString("ErrorTextInvalidStudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Threshold has incorrect format!.
        /// </summary>
        internal static string ErrorTextLowerThresholdFormat {
            get {
                return ResourceManager.GetString("ErrorTextLowerThresholdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer sheets selected!.
        /// </summary>
        internal static string ErrorTextNoAnswerSheetsSelected {
            get {
                return ResourceManager.GetString("ErrorTextNoAnswerSheetsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories configured!.
        /// </summary>
        internal static string ErrorTextNoCategoriesConfigured {
            get {
                return ResourceManager.GetString("ErrorTextNoCategoriesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories selected!.
        /// </summary>
        internal static string ErrorTextNoCategoriesSelected {
            get {
                return ResourceManager.GetString("ErrorTextNoCategoriesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file has been selected!.
        /// </summary>
        internal static string ErrorTextNoFileSelected {
            get {
                return ResourceManager.GetString("ErrorTextNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row has been selected!.
        /// </summary>
        internal static string ErrorTextNoRowSelected {
            get {
                return ResourceManager.GetString("ErrorTextNoRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resized Cell Height has incorrect format!.
        /// </summary>
        internal static string ErrorTextResizedCellHeightFormat {
            get {
                return ResourceManager.GetString("ErrorTextResizedCellHeightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resized Cell Width has incorrect format!.
        /// </summary>
        internal static string ErrorTextResizedCellWidthFormat {
            get {
                return ResourceManager.GetString("ErrorTextResizedCellWidthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubbish Lines Limit has incorrect format!.
        /// </summary>
        internal static string ErrorTextRubbishLinesLimitFormat {
            get {
                return ResourceManager.GetString("ErrorTextRubbishLinesLimitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required answer sheet not found in the database!.
        /// </summary>
        internal static string ErrorTextSheetNotFoundInDatabase {
            get {
                return ResourceManager.GetString("ErrorTextSheetNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student number has not been properly selected!.
        /// </summary>
        internal static string ErrorTextStudentNumberNotSelected {
            get {
                return ResourceManager.GetString("ErrorTextStudentNumberNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student number out of range..
        /// </summary>
        internal static string ErrorTextStudentNumberOutOfRange {
            get {
                return ResourceManager.GetString("ErrorTextStudentNumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Table Columns has incorrect format!.
        /// </summary>
        internal static string ErrorTextStudentTableColumnsFormat {
            get {
                return ResourceManager.GetString("ErrorTextStudentTableColumnsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Table Rows has incorrect format!.
        /// </summary>
        internal static string ErrorTextStudentTableRowsFormat {
            get {
                return ResourceManager.GetString("ErrorTextStudentTableRowsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Count has incorrect format!.
        /// </summary>
        internal static string ErrorTextTableCountFormat {
            get {
                return ResourceManager.GetString("ErrorTextTableCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Line Curvature Limit has incorrect format!.
        /// </summary>
        internal static string ErrorTextTableLineCurvatureLimitFormat {
            get {
                return ResourceManager.GetString("ErrorTextTableLineCurvatureLimitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Line Eccentricity Limit has incorrect format!.
        /// </summary>
        internal static string ErrorTextTableLineEccentricityLimitFormat {
            get {
                return ResourceManager.GetString("ErrorTextTableLineEccentricityLimitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Threshold has incorrect format!.
        /// </summary>
        internal static string ErrorTextUpperThresholdFormat {
            get {
                return ResourceManager.GetString("ErrorTextUpperThresholdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Cell Width has incorrect format!.
        /// </summary>
        internal static string ErrotTextDefaultCellWidthFormat {
            get {
                return ResourceManager.GetString("ErrotTextDefaultCellWidthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers have not been loaded!.
        /// </summary>
        internal static string ExceptionTextCorrectAnswersNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionTextCorrectAnswersNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected answers have not been loaded!.
        /// </summary>
        internal static string ExceptionTextExpectedAnswersNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionTextExpectedAnswersNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klokan - Evaluation - Parameters.
        /// </summary>
        internal static string FormCaptionParameterEditEval {
            get {
                return ResourceManager.GetString("FormCaptionParameterEditEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klokan - Test - Parameters.
        /// </summary>
        internal static string FormCaptionParameterEditTest {
            get {
                return ResourceManager.GetString("FormCaptionParameterEditTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Update.
        /// </summary>
        internal static string InfoCaptionDatabaseUpdated {
            get {
                return ResourceManager.GetString("InfoCaptionDatabaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Filenames.
        /// </summary>
        internal static string InfoCaptionDuplicateFilenames {
            get {
                return ResourceManager.GetString("InfoCaptionDuplicateFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Test Items.
        /// </summary>
        internal static string InfoCaptionNoTestItems {
            get {
                return ResourceManager.GetString("InfoCaptionNoTestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database updated..
        /// </summary>
        internal static string InfoTextDatabaseUpdated {
            get {
                return ResourceManager.GetString("InfoTextDatabaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files were already present in the list, so they were not added..
        /// </summary>
        internal static string InfoTextDuplicateFilenames {
            get {
                return ResourceManager.GetString("InfoTextDuplicateFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no test items to evaluate..
        /// </summary>
        internal static string InfoTextNoTestItems {
            get {
                return ResourceManager.GetString("InfoTextNoTestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Sheet ID.
        /// </summary>
        internal static string OutputTextAnswerSheetID {
            get {
                return ResourceManager.GetString("OutputTextAnswerSheetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string OutputTextCategory {
            get {
                return ResourceManager.GetString("OutputTextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen.
        /// </summary>
        internal static string OutputTextChosen {
            get {
                return ResourceManager.GetString("OutputTextChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string OutputTextCorrect {
            get {
                return ResourceManager.GetString("OutputTextCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string OutputTextPoints {
            get {
                return ResourceManager.GetString("OutputTextPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Number.
        /// </summary>
        internal static string OutputTextStudentNumber {
            get {
                return ResourceManager.GetString("OutputTextStudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string OutputTextYear {
            get {
                return ResourceManager.GetString("OutputTextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Update.
        /// </summary>
        internal static string PromptCaptionDatabaseUpdate {
            get {
                return ResourceManager.GetString("PromptCaptionDatabaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Start.
        /// </summary>
        internal static string PromptCaptionEvaluationStart {
            get {
                return ResourceManager.GetString("PromptCaptionEvaluationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update the database?.
        /// </summary>
        internal static string PromptTextDatabaseUpdate {
            get {
                return ResourceManager.GetString("PromptTextDatabaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start evaluation?.
        /// </summary>
        internal static string PromptTextEvaluationStart {
            get {
                return ResourceManager.GetString("PromptTextEvaluationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap studentTableImage {
            get {
                object obj = ResourceManager.GetObject("studentTableImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Completed.
        /// </summary>
        internal static string SummaryCaption {
            get {
                return ResourceManager.GetString("SummaryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results saved in.
        /// </summary>
        internal static string SummaryTextDatabaseTimePart1 {
            get {
                return ResourceManager.GetString("SummaryTextDatabaseTimePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds..
        /// </summary>
        internal static string SummaryTextDatabaseTimePart3 {
            get {
                return ResourceManager.GetString("SummaryTextDatabaseTimePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation was successful..
        /// </summary>
        internal static string SummaryTextEvaluationSuccessful {
            get {
                return ResourceManager.GetString("SummaryTextEvaluationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation finished in.
        /// </summary>
        internal static string SummaryTextEvaluationTimePart1 {
            get {
                return ResourceManager.GetString("SummaryTextEvaluationTimePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds..
        /// </summary>
        internal static string SummaryTextEvaluationTimePart3 {
            get {
                return ResourceManager.GetString("SummaryTextEvaluationTimePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sheet was not evaluated because of an error..
        /// </summary>
        internal static string SummaryTextFailedSheetPart2 {
            get {
                return ResourceManager.GetString("SummaryTextFailedSheetPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sheets were not evaluated because of an error..
        /// </summary>
        internal static string SummaryTextFailedSheetsPart2 {
            get {
                return ResourceManager.GetString("SummaryTextFailedSheetsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table1Image {
            get {
                object obj = ResourceManager.GetObject("table1Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table2Image {
            get {
                object obj = ResourceManager.GetObject("table2Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table3Image {
            get {
                object obj = ResourceManager.GetObject("table3Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns in an answer table..
        /// </summary>
        internal static string ToolTipAnswerTableColumns {
            get {
                return ResourceManager.GetString("ToolTipAnswerTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows in an answer table..
        /// </summary>
        internal static string ToolTipAnswerTableRows {
            get {
                return ResourceManager.GetString("ToolTipAnswerTableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How bright a shade of grey can be to be recognized as black (the rest will be white)..
        /// </summary>
        internal static string ToolTipBlackWhiteThreshold {
            get {
                return ResourceManager.GetString("ToolTipBlackWhiteThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE - shape recognition; FALSE - pixel ratio.
        /// </summary>
        internal static string ToolTipCellEvaluationType {
            get {
                return ResourceManager.GetString("ToolTipCellEvaluationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How curved a line can be to still be recognized as a straight line (1 is minimum)..
        /// </summary>
        internal static string ToolTipCrossLineCurvatureLimit {
            get {
                return ResourceManager.GetString("ToolTipCrossLineCurvatureLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of lines to be detected..
        /// </summary>
        internal static string ToolTipCrossLineLength {
            get {
                return ResourceManager.GetString("ToolTipCrossLineLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every cell will be resized to have this height..
        /// </summary>
        internal static string ToolTipDefaultCellHeight {
            get {
                return ResourceManager.GetString("ToolTipDefaultCellHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every cell will be resized to have this width..
        /// </summary>
        internal static string ToolTipDefaultCellWidth {
            get {
                return ResourceManager.GetString("ToolTipDefaultCellWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every sheet will be resized accordingly (preserving aspect ratio) before the tables are extracted..
        /// </summary>
        internal static string ToolTipDefaultSheetWidth {
            get {
                return ResourceManager.GetString("ToolTipDefaultSheetWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the ratio of pixels representing student input in the whole cell is lower than this, answer was not chosen..
        /// </summary>
        internal static string ToolTipLowerThreshold {
            get {
                return ResourceManager.GetString("ToolTipLowerThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the height of a cell after the sheet has been resized (see default_sheet_height)..
        /// </summary>
        internal static string ToolTipResizedCellHeight {
            get {
                return ResourceManager.GetString("ToolTipResizedCellHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the width of a cell after the sheet has been resized (see default_sheet_width)..
        /// </summary>
        internal static string ToolTipResizedCellWidth {
            get {
                return ResourceManager.GetString("ToolTipResizedCellWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of lines that don&apos;t form a cross that will be ignored and not considered as a correction..
        /// </summary>
        internal static string ToolTipRubbishLinesLimit {
            get {
                return ResourceManager.GetString("ToolTipRubbishLinesLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns in the student number table..
        /// </summary>
        internal static string ToolTipStudentTableColumns {
            get {
                return ResourceManager.GetString("ToolTipStudentTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows in the student number table..
        /// </summary>
        internal static string ToolTipStudentTableRows {
            get {
                return ResourceManager.GetString("ToolTipStudentTableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of tables in the answer sheet..
        /// </summary>
        internal static string ToolTipTableCount {
            get {
                return ResourceManager.GetString("ToolTipTableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How curved a line can be to still be recognized as a straight line (1 is minimum)..
        /// </summary>
        internal static string ToolTipTableLineCurvatureLimit {
            get {
                return ResourceManager.GetString("ToolTipTableLineCurvatureLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How slanted a line can be to be recognized as either horizontal or vertical (in radians)..
        /// </summary>
        internal static string ToolTipTableLineEccentricityLimit {
            get {
                return ResourceManager.GetString("ToolTipTableLineEccentricityLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the ratio of pixels representing student input in the whole cell is higher than this, answer was invalidated..
        /// </summary>
        internal static string ToolTipUpperThreshold {
            get {
                return ResourceManager.GetString("ToolTipUpperThreshold", resourceCulture);
            }
        }
    }
}
