#ifndef PARAMETERS_
#define PARAMATERS_

const int CROSS_LINE_LENGTH = 35;
const int TABLE_LINE_LENGTH = 350;
const float TABLE_LINE_ECCENTRICITY_LIMIT = CV_PI / 8;
const int BLACK_WHITE_THRESHOLD = 230;
const int RUBBISH_LINES_LIMIT = 10;

#endif // !PARAMETERS_
